[package]
rust-version.workspace = true
name = "sdkwork-catalog-service-host"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true


[lints]
workspace = true
[lib]
path = "src/lib.rs"

[dependencies]
dotenvy.workspace = true
sdkwork-database-config.workspace = true
sdkwork-database-id.workspace = true
sdkwork-database-sqlx.workspace = true
sdkwork-web-bootstrap.workspace = true
sdkwork-web-core.workspace = true
tracing.workspace = true
